clipped: True
use_agent_id: False
train: True
fully_observed: False
num_relevant_agents: all
num_test_candidates: 10
num_train_candidates: 40
traits:
  lumber:
    distribution: 'uniform'
    low: 0.0
    high: 10.0
  water:
    distribution: 'uniform'
    low: 0.0
    high: 10.0
