#This, along with every other default_xxx_config.yaml should only be used with generate_config.py
#The configs that should be used are in the subfolders in this folder
clipped: True
use_agent_id: False
train: True
fully_observed: True #If false, agents do not share observations at all 
num_relevant_agents: 2
num_test_candidates: 10
num_train_candidates: 40
traits:
  sensing_rad:
    distribution: 'normal'
    loc: 0.2
    scale: 0.1
  capture_rad:
    distribution: 'normal'
    loc: .1
    scale: .05
    

