# --- IPPO specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "episode"

buffer_size: 10
batch_size_run: 1
batch_size: 1

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 0.01


lr: 0.0003

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

# use IA2C
agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.01
standardise_returns: False
standardise_rewards: True
use_rnn: False
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "ac_critic"
epochs: 4
eps_clip: 0.2
name: "ippo"

agent: "mlp"
use_gnn: True
msg_out_size: 64
num_layers: 1 # number of hops for communication
encoder: "mlp"
separated_policy: True # make the gnn for comm separate from the action network. Thus actor and critic get the same input

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.01
epsilon_anneal_time: 10000
evaluation_epsilon: 0.0

# Testing options
test_greedy: True
test_nepisode: 2
test_interval: 1
log_interval: 1
runner_log_interval: 1
learner_log_interval: 1
t_max: 10000