# --- MAPPO specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 64
batch_size_run: 64
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0005

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.001
use_rnn: False
use_gnn: False #Weird things happen when this is true... The code working is not one of them :/
standardise_returns: False
standardise_rewards: False
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 4
eps_clip: 0.2
name: "mappo"

agent: "gnn"
num_layers: 1
encoder: "mlp" # default to mlp, gru takes much longer to train

# action_selector: "epsilon_greedy"
# epsilon_start: 1.0
# epsilon_finish: 0.01
# epsilon_anneal_time: 50000
# evaluation_epsilon: 0.0

t_max: 20050000

# checkpoint_path: "/home/dwalkerhowell3/star_lab/ca-gnn-marl/results/models/2023-05-22:11-18-33-AM__mappo__robotarium_gym:PredatorCapturePreyGNN-v0"
# load_step: 0
# evaluate: False
# restart_from_pretrained: True
