# --- MAPPO specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0005

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.01
use_rnn: False
use_gnn: True #Weird things happen when this is true... The code working is not one of them :/
standardise_returns: True
standardise_rewards: False
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 4
eps_clip: 0.2
name: "mappo"

agent: "gnn"
num_layers: 2
encoder: "gru"

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.01
epsilon_anneal_time: 10000
evaluation_epsilon: 0.0

t_max: 2000000
